public class partyPageController {
    // There isn't much going on in here.
    // We want to query for things (parties, characters, etc.) in user context, not system context.
    // This way, users will only see items that they have permission to see.
    // Because of this, most of our functionality will be located in the extender, not the controller.
    
    public partyPageController() {
        
    }
    
}